name: Prefetcharr
description: >
  Automatically have Sonarr fetch the next episodes of the show you're
  watching on Jellyfin, Emby, or Plex.
version: "1.4.1"
slug: prefetcharr
url: https://github.com/p-hueber/prefetcharr
init: false
arch:
  - amd64

options:
  media_server_type: "Jellyfin"
  media_server_url: "http://homeassistant.local:8096"
  media_server_api_key: ""
  sonarr_url: "http://homeassistant.local:8989"
  sonarr_api_key: ""
  interval: 900
  prefetch_num: 2
  request_seasons: true
  connection_retries: 6
  log_level: "Info"
  users: ""
  libraries: ""

schema:
  media_server_type: list(Jellyfin|Emby|Plex|Tautulli)
  media_server_url: "url"
  media_server_api_key: "str"
  sonarr_url: "url"
  sonarr_api_key: "str"
  interval: "int"
  prefetch_num: "int"
  request_seasons: "bool"
  connection_retries: "int"
  log_level: list(Trace|Debug|Info|Warn|Error)
  users: "str?"
  libraries: "str?"
