name: "SubGen - Whisper Subtitles for Bazarr"
description: "Automatically generates subtitles using OpenAI Whisper via the ASR API. Can be used as a subtitle provider in Bazarr."
version: "1.1.1"
slug: "subgen-addon"
memory: 0
init: false
arch:
  - amd64
  - aarch64
ports:
  9000/tcp: 9000
ports_description:
  9000/tcp: "ASR webservice port (use this in Bazarr)"
options:
  WHISPER_MODEL: "medium"
  COMPUTE_TYPE: "int8"
  TRANSCRIBE_DEVICE: "cpu"
  CONCURRENT_TRANSCRIPTIONS: "1"
  WHISPER_THREADS: "4"
  TRANSCRIBE_OR_TRANSLATE: "translate"
  SKIP_LANGUAGE_DETECT: "true"
  WEBHOOKPORT: "9000"
  DEBUG: false
schema:
  WHISPER_MODEL: "list(tiny|base|small|medium|large-v2|large-v3|distil-large-v3)"
  COMPUTE_TYPE: "list(int8|float16|float32|int8_float16)"
  TRANSCRIBE_DEVICE: "list(cpu|cuda)"
  CONCURRENT_TRANSCRIPTIONS: "str"
  WHISPER_THREADS: "str"
  TRANSCRIBE_OR_TRANSLATE: "list(transcribe|translate)"
  SKIP_LANGUAGE_DETECT: "bool"
  WEBHOOKPORT: "str"
  DEBUG: "bool"
